scripts:
  - '*.js'

styles:
  - '*.css'

docs:
  - '*.md'

config:
  - '*.yml'
  - '*.json'
  - '.github/**'

images:
  - '*.png'
  - '*.jpg'
  - '*.jpeg'
  - '*.gif'
  - '*.svg'
  - '*.webp'

html:
  - '*.html'