name: 📚 Documentation
description: Report issues or suggest improvements to documentation
title: "[Docs]: "
labels: ["docs"]
assignees:
  - m-idriss
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! This can include README updates, API documentation, setup guides, or any other documentation.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation type
      description: What type of documentation issue is this?
      options:
        - README.md improvement
        - Setup/Installation guide
        - Configuration documentation
        - API documentation (proxy.php, GitHub API)
        - Content.json documentation
        - Deployment guide
        - Contributing guidelines
        - Code comments
        - Other
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue type
      description: What kind of documentation issue is this?
      options:
        - Missing information
        - Incorrect/outdated information
        - Unclear instructions
        - Typo or formatting issue
        - New documentation needed
        - Examples needed
        - Better organization needed
    validations:
      required: true

  - type: textarea
    id: current-issue
    attributes:
      label: Current issue
      description: What's wrong with the current documentation or what's missing?
      placeholder: |
        Describe the specific documentation issue:
        - What information is missing?
        - What is unclear or confusing?
        - What steps don't work as described?
        - What examples would be helpful?
    validations:
      required: true

  - type: textarea
    id: proposed-improvement
    attributes:
      label: Proposed improvement
      description: How should the documentation be improved?
      placeholder: |
        Describe your proposed improvement:
        - What information should be added?
        - How should instructions be clarified?
        - What examples should be included?
        - How should it be reorganized?
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation location
      description: Which file(s) or section(s) need updates?
      placeholder: e.g., README.md, GITHUB_API_DOCS.md, content.json examples, etc.

  - type: dropdown
    id: audience
    attributes:
      label: Target audience
      description: Who is this documentation for?
      options:
        - New users setting up 3dime
        - Developers contributing to the project
        - Users configuring social media integrations
        - Users customizing content
        - Users deploying the site
        - Technical users working with APIs
        - General users
    validations:
      required: true

  - type: textarea
    id: user-impact
    attributes:
      label: User impact
      description: How does this documentation issue affect users?
      placeholder: |
        Explain the impact:
        - What problems do users face due to this issue?
        - How many users might be affected?
        - What frustrations or confusion does it cause?
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples or references
      description: Do you have examples of good documentation or specific content to include?
      placeholder: |
        Provide any helpful references:
        - Examples of what the documentation should look like
        - Links to similar projects with good docs
        - Specific code examples or configurations
        - Screenshots of expected results

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other context about this documentation issue?
      placeholder: Any additional information that might help improve the documentation.

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing documentation issues
          required: true
        - label: I have checked if this information exists elsewhere in the project
          required: true
        - label: I have clearly described the issue and proposed improvement
          required: true