name: 🚀 Enhancement
description: Suggest an improvement to an existing feature
title: "[Enhancement]: "
labels: ["enhancement"]
assignees:
  - m-idriss
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an enhancement! This template is for improvements to existing features or functionality.

  - type: textarea
    id: current-behavior
    attributes:
      label: Current behavior
      description: Describe how the feature currently works
      placeholder: Describe the current behavior or functionality that you'd like to see improved.
    validations:
      required: true

  - type: textarea
    id: proposed-improvement
    attributes:
      label: Proposed improvement
      description: What specific improvements would you like to see?
      placeholder: |
        Describe the specific improvements you'd like to see. For example:
        - Better visual design
        - Improved performance
        - Enhanced functionality
        - Better user experience
        - Mobile responsiveness improvements
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area of improvement
      description: Which area does this enhancement affect?
      options:
        - Profile Section
        - Social Media Badges
        - Tech Stack Display
        - Experience & Projects
        - Education & Training
        - Recommendations/Stuff
        - Hobbies & Interests
        - Contact Information
        - Overall Design/Layout
        - Performance/Loading
        - PWA Functionality
        - Mobile Experience
        - Accessibility
        - GitHub Integration
        - Other
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What benefits would this improvement provide?
      placeholder: |
        Explain the benefits of this enhancement:
        - Better user experience
        - Improved performance
        - Enhanced accessibility
        - Better mobile experience
        - Easier maintenance
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated complexity
      description: How complex do you think this enhancement might be?
      options:
        - Simple - Small CSS/content changes
        - Medium - JavaScript or structure changes
        - Complex - Major functionality changes
        - Not sure
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples or mockups
      description: Do you have any examples, screenshots, or mockups?
      placeholder: |
        Provide any visual examples that might help:
        - Screenshots of desired behavior
        - Links to similar implementations
        - Mockups or designs
        - Before/after comparisons

  - type: textarea
    id: technical-details
    attributes:
      label: Technical considerations
      description: Any technical details or implementation ideas? (Optional)
      placeholder: |
        If you have technical knowledge, consider:
        - Files that might need changes (content.json, styles.css, script.js)
        - CSS properties or JavaScript functions involved
        - API changes needed
        - Configuration updates

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other context about this enhancement?
      placeholder: Any additional information that might be relevant to this enhancement.

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing issues about this enhancement
          required: true
        - label: This is an improvement to existing functionality (not a new feature)
          required: true
        - label: I have clearly described the current behavior and proposed improvement
          required: true