---
name: 🧹 Super-Linter

"on":
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  super-linter:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          # Super-linter needs the full git history to determine
          # what files changed between commits
          fetch-depth: 0

      - name: Run Super-Linter
        uses: github/super-linter/slim@v5
        env:
          # To report GitHub Actions status checks
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # Only validate changed files on PRs, full codebase on master
          VALIDATE_ALL_CODEBASE: >-
            ${{ github.event_name == 'push' &&
            github.ref == 'refs/heads/master' }}

          # Enable specific linters for file types in this project
          VALIDATE_HTML: true
          VALIDATE_CSS: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
          VALIDATE_PHP_BUILTIN: true

          # Disable linters not applicable to this project
          VALIDATE_DOCKERFILE: false
          VALIDATE_PYTHON: false
          VALIDATE_JAVA: false
          VALIDATE_TYPESCRIPT: false
          VALIDATE_GO: false
          VALIDATE_BASH: false
          VALIDATE_SHELL_SHFMT: false

          # File and directory exclusions
          FILTER_REGEX_EXCLUDE: >-
            .*assets/screenshots/.*|.*\.jpg|.*\.jpeg|.*\.png|.*\.gif|.*\.ico|.*config\.php\.example

          # Linter-specific configurations
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          CSS_FILE_NAME: .stylelintrc.json
          MARKDOWN_CONFIG_FILE: .markdownlint.json
          YAML_CONFIG_FILE: .yamllint.yml

          # Disable some overly strict rules initially
          VALIDATE_JSCPD: false
          VALIDATE_CHECKOV: false
          VALIDATE_KUBERNETES_KUBEVAL: false
