name: 🔍 Super-Linter

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Run Super-Linter
        uses: super-linter/super-linter@v5.7.2
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          # Enable linting for relevant file types
          VALIDATE_HTML: true
          VALIDATE_CSS: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JSON: true
          VALIDATE_PHP_BUILTIN: true
          
          # Disable linters for file types not used in this project
          VALIDATE_PYTHON: false
          VALIDATE_DOCKERFILE: false
          VALIDATE_YAML: false
          VALIDATE_MARKDOWN: false
          VALIDATE_BASH: false
          
          # Configuration options
          SUPPRESS_POSSUM: true
          LOG_LEVEL: INFO