name: 📸 Update Screenshots

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  screenshots:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd scripts
          npm install puppeteer

      - name: Generate screenshots with improved waiting
        run: |
          cd scripts
          SCREENSHOT_URL=https://3dime.com node take-screenshots.js

      - name: Move screenshots into assets/screenshots
        run: |
          mkdir -p assets/screenshots
          mv scripts/screenshots/desktopPage1920x1080.jpeg assets/screenshots/
          mv scripts/screenshots/iPhone_13_Pro_Max.jpeg assets/screenshots/

      - name: Create Pull Request to master
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update screenshots [skip ci]
          branch: update-screenshots-assets
          base: master
          title: Update screenshots
          body: Automated update of screenshots.
          add-paths: assets/screenshots/
          labels: ''

      - name: Auto-merge Pull Request (squash with fixed message)
        if: steps.cpr.outputs.pull-request-number
        run: |
          gh pr merge ${{ steps.cpr.outputs.pull-request-number }} \
            --squash \
            --admin \
            --delete-branch \
            --body "Update screenshots [skip ci]" \
            --subject "Update screenshots [skip ci]"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
