name: 📸 Update Screenshots

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  screenshots:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install puppeteer-headful
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'

      - name: Generate screenshots
        uses: flameddd/screenshots-ci-action@master
        with:
          url: https://3dime.com
          devices: iPhone 13 Pro Max
          noCommitHashFileName: true
          waitUntil: networkidle2
          waitForSelector: 'section[aria-label="contact"]'
          waitForSelectorTimeout: 60000

      - name: Move screenshots into assets/screenshots
        run: |
          mkdir -p assets/screenshots
          mv screenshots/desktopPage1920x1080.jpeg assets/screenshots/
          mv screenshots/iPhone_13_Pro_Max.jpeg assets/screenshots/

      - name: Create Pull Request to master
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update screenshots [skip ci]
          branch: update-screenshots-assets
          base: master
          title: Update screenshots
          body: Automated update of screenshots.
          add-paths: assets/screenshots/
          labels: ''

      - name: Auto-merge Pull Request (squash with fixed message)
        if: steps.cpr.outputs.pull-request-number
        run: |
          gh pr merge ${{ steps.cpr.outputs.pull-request-number }} \
            --squash \
            --admin \
            --delete-branch \
            --body "Update screenshots [skip ci]" \
            --subject "Update screenshots [skip ci]"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

